version: 2
jobs:
  build_cen:
    docker:
      - image: circleci/golang:1.9
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    working_directory: /go/src/github.com/ronaudinho/micromonopipe
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: install pip
        command: sudo apt-get update && sudo apt-get install python-pip python-dev
      - run:
        name: install awscli
        command: sudo pip install awscli
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: go test -v ./...
      - run: cd cmd/cen && go build
      # push to ecr and stuff
  # more jobs for other services
  # TODO staging/production and services separation
  deploy_cen:
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: install awscli
        command: sudo pip install awscli
      # pull from ecr and run
workflows:
  version: 2
  build_cen:
    jobs:
      - build_cen
  build_and_deploy_cen_staging:
    jobs:
      - build_cen
      - deploy_cen:
        requires:
          - build_cen
        filters:
          branches:
            only: staging
  build_and_deploy_cen_production:
    jobs:
      - build_cen
      - deploy_cen:
        requires:
          - build_cen
        filters:
          branches:
            only: master
